export const baseURL = 'https://www.eventwheel.ca/';
export const serviceCharge = 1.39;

export const eventTypes = [
	'Appearance or Singing',
	'Attraction',
	'Camp, Trip, or Retreat',
	'Class, Training, or Workshop',
	'Concert or Performance',
	'Conference',
	'Convention',
	'Dinner or Gala',
	'Festival or Fair',
	'Game or Competition',
	'Meeting or Networking Event',
	'Party or Social Gathering',
	'Race or Endurance Event',
	'Rally',
	'Screening',
	'Seminar or Talk',
	'Tour',
	'Tournament',
	'Trade Show, Consumer Show or Expo',
	'Other'
];

export const eventCategories: {
	[key: string]: string[];
} = {
	'Auto, Boat & Air': [
		'Air',
		'Auto',
		'Boat',
		'Motorcycle/ATV',
		'Other'
	],
	'Business & Professional': [
		'Career',
		'Design',
		'Educators',
		'Environment & Sustainability',
		'Finance',
		'Investment',
		'Media',
		'Non Profit & NGOs',
		'Other',
		'Real Estate',
		'Sales & Marketing',
		'Startups & Small Business'
	],
	'Charity & Causes': [
		'Animal Welfare',
		'Disaster Relief',
		'Education',
		'Environment',
		'Health Care',
		'Human Rights',
		'International Aid',
		'Other',
		'Poverty'
	],
	'Community & Culture': [
		'City/town',
		'County',
		'Heritage',
		'Historic',
		'LGBT',
		'Language',
		'Medieval',
		'Nationality',
		'Other',
		'Renaissance',
		'State'
	],
	'Family & Education': [
		'Alumin',
		'Baby',
		'Children & Youth',
		'Education',
		'Other',
		'Parenting',
		'Parents Association',
		'Reunion',
		'Senior Citizen'
	],
	'Fashion & Beauty': [
		'Accessories',
		'Beauty',
		'Bridal',
		'Fashion',
		'Other'
	],
	'Film, Media & Entertainment': [
		'Adult',
		'Anime',
		'Comedy',
		'Comics',
		'Film',
		'Gaming',
		'Other',
		'TV'
	],
	'Food & Drink': [
		'Beer',
		'Food',
		'Other',
		'Spirits',
		'Wine'
	],
	'Government & Politics': [
		'County/Municipal Government',
		'Democratic Party',
		'Federal Government',
		'International Affairs',
		'Military',
		'National Security',
		'Non-partisan',
		'Other',
		'Other Party',
		'Republican Party',
		'State Government'
	],
	'Health & Wellness': [
		'Medical',
		'Mental Health',
		'Other',
		'Personal Health',
		'Spa Yoga'
	],
	'Hobbies & Special Interest': [
		'Adult',
		'Anime/Comics',
		'Books',
		'DIY',
		'Drawing & Painting',
		'Gaming',
		'Knitting',
		'Other',
		'Photography'
	],
	'Home & Lifestyle': [
		'Dating',
		'Home & Garden',
		'Other',
		'Pets & Animals'
	],
	Music: [
		'Acoustic',
		'Alternative',
		'Americana',
		'Bluegrass',
		'Blues',
		'Blues & Jazz',
		'Classical',
		'Country',
		'Cultural',
		'DJ/Dance',
		'EDM',
		'EDM/Electronic',
		'Electronic',
		'Experimental',
		'Folk',
		'Hip Hop / Rap',
		'Indie',
		'Jazz',
		'Latin',
		'Metal',
		'Opera',
		'Other',
		'Pop',
		'Psychedelic',
		'Punk/Hardcore',
		'R & B',
		'Reggae',
		'Religious/Spiritual',
		'Rock',
		'Singer/Song writer',
		'Top 40',
		'World'
	],
	'Performing & Visual Arts': [
		'Ballet',
		'Comedy',
		'Craft',
		'Dance',
		'Design',
		'Fine Art',
		'Jewelry',
		'Literary Arts',
		'Musical',
		'Opera',
		'Orchestra',
		'Other',
		'Painting',
		'Sculpture',
		'Theatre'
	],
	'Religion & Spirituality': [
		'Agnosticism',
		'Atheism',
		'Buddhism',
		'Christianity',
		'Eastern Religion',
		'Folk Religions',
		'Hinduism',
		'Islam',
		'Judaism',
		'Mormonism',
		'Mysticism & Occult',
		'New Age',
		'Other',
		'Shintoism',
		'Sikhism',
		'Unaffiliated'
	],
	'School Activities': [
		'After School Care',
		'Dinner',
		'Fund Raiser',
		'Parking',
		'Public Speaker',
		'Raffle'
	],
	'Science & Technology': [
		'Biotech',
		'High Tech',
		'Medicine',
		'Mobile',
		'Other',
		'Robotics',
		'Science',
		'Social Media'
	],
	'Seasonal & Holiday': [
		'Channukah',
		'Christmas',
		'Easter',
		'Fall Events',
		'Halloween/Haunt',
		'Independence day',
		'New years Eve',
		'Other',
		'St Patricks Day',
		'Thanksgiving'
	],
	'Sports & Fitness': [
		'Baseball',
		'Basketball',
		'Camps',
		'Cheer',
		'Cycling',
		'Exercise',
		'Fighting & Martial Arts',
		'Football',
		'Golf',
		'Hockey',
		'Lacrosse',
		'Motor Sports',
		'Mountain Biking',
		'Obstacles',
		'Others',
		'Rugby',
		'Running',
		'Snow Sports',
		'Soccer',
		'Softball',
		'Swimming & Water Sports',
		'Tennis',
		'Track & Field',
		'Volley ball',
		'Walking',
		'Weightlifting',
		'Wrestling',
		'Yoga'
	],
	'Travel & Outdoor': [
		'Canoeing',
		'Climbing',
		'Hiking',
		'Kayaking',
		'Other',
		'Rafting',
		'Travel'
	],
	Other: []
};
